### ISSUE TITLE
definition of ZIsDistance missing

### ISSUE THREAD

**Issue by linojon** [googlevr/tilt-brush-toolkit#10]
Receive this error just opening in unity (2017.2.0p2) the toolkit (tiltbrushtoolkit-UnitySDK-v14.0.0.unitypackage)

Assets/TiltBrush/Scripts/Editor/ModelImportSettings.cs(226,46): error CS0117: `TiltBrushToolkit.BrushDescriptor.Semantic' does not contain a definition for `ZIsDistance'

**Comment by dubois** [comment]
That's defined on line 28 of Assets/TiltBrush/Scripts/BrushDescriptor.cs. You probably have a duplicate definition somewhere, perhaps from importing Poly Toolkit. Poly Toolkit and Tilt Brush Toolkit cannot currently coexist in the same Unity project, at least not easily.

It may work if you do something like this:
- import Poly Toolkit first, which has its own copy of TBT in Assets/PolyToolkit/Internal/tbt
- import Tilt Brush Toolkit (but only those files which haven't already been imported by Poly Toolkit)
- the "ZIsDistance" compile error. Either search-and-replace "Semantic.ZIsDistance" with "Semantic.XyIsUvZIsDistance", or add a definition for that enum value here:

Assets/PolyToolkit/Internal/tbt/Scripts/BrushDescriptor.cs line 28

    XyIsUvZIsDistance,
    ZIsDistance = XyIsUvZIsDistance,   // <-- add this line

If that works out for you, I can patch TBT so this works a bit better out of the box.

**Comment by linojon** [comment]
Correct. I was playing with both sdk, separately but in the same project. I have no need for both in the same project and trying them in separate projects worked fine. Thanks.
