### ISSUE TITLE
Relationship between this repo and poly-toolkit-unity

### ISSUE THREAD

**Issue by andybak** [googlevr/tilt-brush-toolkit#12]
There's considerable overlap of functionality between this repo and poly-toolkit-unity (I'm assuming that poly-toolkit-unity is a superset of the functionality here).

Will they always be updated in sync? If I want the most up to date Tilt Brush import code should I check here?

**Comment by dubois** [comment]
Poly Toolkit is generally simpler to use and we recommend it over TBT.

However, we plan to keep TBT around for those people who have specialized
reasons for preferring fbx, or who need workflows that don't involve
uploading content to Poly.

p

**Comment by dubois** [comment]
And yes, when one is updated with new TB shaders or shader fixes, the other
will be as well.

**Comment by andybak** [comment]
Great. Thanks. 

Might be worth adding something like this to the readme of both projects.

**Comment by dubois** [comment]
Good idea. I thought we did have language to this effect somewhere in Poly
Toolkit; let's leave this issue open to remind me to make the changes.

**Comment by dubois** [comment]
Updated readme.md
