### ISSUE TITLE
export sequence

### ISSUE THREAD

**Issue by subzero911** [googlevr/tilt-brush-toolkit#13]
It is written in your documentation: "Export each frame in Tilt Brush and copy them into the project" in order to create an animation.
How to do it? I can export only a final result FBX from the TiltBrush inteface. Please provide a step-by-step instruction.

**Comment by dubois** [comment]
Hi. Tilt Brush has no animation support. You will have to draw each frame
by hand.

**Comment by subzero911** [comment]
I want to create an animation in Unity like in this video: [https://youtu.be/2qRQsiaFEvw](url) . The process of model painting from scratch. Do you have any suggestions?

**Comment by dubois** [comment]
That video looks like it was made with the Tilt Brush video camera or with
desktop screen-recording software, not with Unity or the Toolkit.

To get the video camera, select the camera tool, then swipe to switch modes.

Then, load your sketch from the sketchbook and it will draw slowly like in
that video.
