### ISSUE TITLE
Occulus / HTC

### ISSUE THREAD

**Issue by mimicrie** [googlevr/tilt-brush-toolkit#20]
Thank you so much for this incredible work- fantastic!

However, I just failed to implement your teleporting example into a oculus experience (instead of using SteamVR cameraRig). Any idea how to proceed? Thank you so much!

**Comment by dubois** [comment]
Hi, you're welcome!

Unfortunately, we won't be porting any of the example code to new VR APIs like OVR. The main reason the Toolkit exists is to help you bring Tilt Brush .fbx files into Unity. Those examples are meant as inspiration only.

However, the SteamVR API does work with all major headsets that I know of, including Oculus and Windows Mixed Reality; so at least you can try out the example and see how it works.

**Comment by mimicrie** [comment]
Ok, thank you very much for your help!
Looking forward working with the toolkit. 

Best, 
Diana
