### ISSUE TITLE
Brushes with Light material are not rendered as in Tiltbrush.

### ISSUE THREAD

**Issue by amrittb** [googlevr/tilt-brush-toolkit#23]
When exported a scene with Light brush to unity, they are overexposed and colors are clamped to white. Any solutions to this?

**Comment by jcowles** [comment]
I believe this is working as expected. The light brush is HDR and the true color only becomes apparent when either using tone mapping or a bloom filter, like Sonic Ether [Natural Bloom & Dirty Lens](https://assetstore.unity.com/packages/vfx/shaders/fullscreen-camera-effects/se-natural-bloom-dirty-lens-17324)

If you apply bloom, does it look how you would expect?

**Comment by amrittb** [comment]
Thanks. It's working after adding Post processing mentioned in the docs.
