### ISSUE TITLE
Change brush colour in Unity

### ISSUE THREAD

**Issue by HelloOrwell** [googlevr/tilt-brush-toolkit#25]
I'm having an impossible time locating where in the code I can possibly make a change to the colour of the disco brush after it's already imported into Unity. This got me thinking how convenient it would be to be to have this added to the toolkit overall. If this isn't something thought to be added to future releases, can I at least get pointed in the right direction where I could make this change myself?

**Comment by dubois** [comment]
The color is embedded in the mesh; it's in the vertex color channel. In Unity, access this via mesh.colors. The only convenient way to change the color is to modify the sketch while it's still in Tilt Brush.
