### ISSUE TITLE
Current release exports Project Settings, which overrides Project Settings in imported project

### ISSUE THREAD

**Issue by dustinfreeman** [googlevr/tilt-brush-toolkit#3]
![tiltbrushimport](https://cloud.githubusercontent.com/assets/940836/22405498/b61653f0-e611-11e6-9b91-cf00cfb8b712.PNG)

This may be fixable by changing usage of `ExportPackageOptions.IncludeLibraryAssets`, [which I see we're not sure about anyway](https://github.com/googlevr/tilt-brush-toolkit/blob/master/UnitySDK/Assets/Editor/BuildPackage.cs#L79). I haven't tried different options yet.

**Comment by dubois** [comment]
Fixed in v11.
