### ISSUE TITLE
Light brush

### ISSUE THREAD

**Issue by 720bit** [googlevr/tilt-brush-toolkit#32]
light brush import to unity error. doesn't make the glow action. Any comments on this?

**Comment by dubois** [comment]
The glow in Tilt Brush is a postprocess effect, and not part of the brush
material. We recommend trying SE Natural Bloom, available on the asset
store.

p

**Comment by andybak** [comment]
Curious. Why recommend a paid asset over Unity's built in post processing bloom?

**Comment by dubois** [comment]
Just what I'm familiar with.
