### ISSUE TITLE
Play mode error when SteamVR is imported 

### ISSUE THREAD

**Issue by chiarashim** [googlevr/tilt-brush-toolkit#34]
Hi, an issue I am having is that when I import the SteamVR plugin, there are a number of compiler errors in the console which prevent me from playing the scene. All I have in the scene is a camera rig, a directional light, and a Tilt brush export. My apologies, I am new to coding, VR, Unity and Github. It seems to work fine before I import the SteamVR plugin. 

Thank you in advance!

![64688033_448001302428883_6053880038640582656_n](https://user-images.githubusercontent.com/51948797/59722987-46522f00-9279-11e9-986b-856e775fece8.png)

**Comment by HelloOrwell** [comment]
I've actually ran into the same problem and do not have the confidence in my troubleshooting enough to fix it after trying and failing more or less. I thought it was something on my end. Switched back to the old SteamVR pkg after that for all my VR projects :(

**Comment by dubois** [comment]
Hi. On the one hand Assets/TiltBrushExamples directory is extremely old and no longer compiles with the latest SteamVR. Since it doesn't really have anything to do with being able to import Tilt Brush .fbx files into Unity, we'll probably delete it from any future .unitypackages we build.

Even without that code, you'll be able to take a fbx, drop it into your Assets folder, and get all the Tilt Brush materials and shaders properly assigned to it.

**Comment by chiarashim** [comment]
> Hi. On the one hand Assets/TiltBrushExamples directory is extremely old and no longer compiles with the latest SteamVR. Since it doesn't really have anything to do with being able to import Tilt Brush .fbx files into Unity, we'll probably delete it from any future .unitypackages we build.
> 
> Even without that code, you'll be able to take a fbx, drop it into your Assets folder, and get all the Tilt Brush materials and shaders properly assigned to it.

Thank you for your help. To clarify, I should import the TiltBrush SDK, except the Assets/TiltBrushExamples. And I should be able to import the fbx file and it will animate/run with the latest Steam VR plugin.

**Comment by dubois** [comment]
Yes, that's correct; except the the fbx importer doesn't require the SteamVR plugin. Only that old example code required it. Here are the simplest steps to get up and running:

- Start a new project
- Import the .unitypackage, ignoring Assets/TiltBrushExamples
- Drop a Tilt Brush .fbx into your project

**Comment by mahe373662858** [comment]
Hello, there is a question I want to ask
Tilt brush unity sdk, this plug-in imported into unit, dynamic loading of FBX exported by Tilt Brush into the project through code in unit, error occurred. Is there a feasible way?

**Comment by dubois** [comment]
Should be fixed with latest .unitypackage
