### ISSUE TITLE
Electricity shader is always out of focus when using Depth of Field standard effect asset

### ISSUE THREAD

**Issue by kaze0** [googlevr/tilt-brush-toolkit#4]
When applying the Depth of Field image effect from the Unity Effects asset package, all electricity elements are out of focus. 

A sample project exhibiting this issue can be found here https://github.com/kaze0/Tilt-Brush-Toolkit-Issue
This sample porject has a Main Camera, with the modern Depth of Field image effect applied.
A small cube was placed inside of the electricity element that was exported from tilt brush, then the depth of field effect was set to target the cube as a way of ensuring that a useful transform was being targeted. You'll notice that the cube is in focus, but the electricity is not. 

I have also moved a splatter paint element, that was exported from tilt brush, into that area as well. The splatter element is in focus as well.

As set up in this test project, I would expect the electricity to be in focus.

Most brush strokes seem to work fine. Disco might be another problematic one, but I haven't had time to take a second look.

Please see project at https://github.com/kaze0/Tilt-Brush-Toolkit-Issue

Sample showing the in focus cube + splatter and out of focus electricity. Zoomed in for effect.
![image](https://cloud.githubusercontent.com/assets/143783/22426902/2849a068-e6cf-11e6-95e4-a0563beb0613.png)

**Comment by dubois** [comment]
Standard depth-of-field implementations have the drawback that they only operate on geometry that writes depth. This means they won't work on transparent or additive geometry.
