### ISSUE TITLE
The display of some brushes are different in u3d and tilt brush

### ISSUE THREAD

**Issue by summerice021** [googlevr/tilt-brush-toolkit#44]
I have use what you point to me in my scirpt. See the following:
https://support.google.com/tiltbrush/thread/27647682?hl=en

But today ,I found the question:

The display of brushes ,such as light,Steamers,waveform,seem too white in unity3d editor,which this is totally differenct from what they look like in tilt brush

You can see the situation in the following:
https://www.youtube.com/watch?v=aL_o44lG2zk

Can you give me some advice on how to improve it to make it behave like in tilt brush.

Thank you very much!

**Comment by dubois** [comment]
Tilt Brush uses a bloom postprocess pass which is where most of the color comes from. The strokes themselves saturate very quickly to white. See the "Bloom" section of [the documentation](https://docs.google.com/document/d/1YID89te9oDjinCkJ9R65bLZ3PpJk1W4S1SM2Ccc6-9w) for more details.

**Comment by summerice021** [comment]
> Tilt Brush uses a bloom postprocess pass which is where most of the color comes from. The strokes themselves saturate very quickly to white. See the "Bloom" section of [the documentation](https://docs.google.com/document/d/1YID89te9oDjinCkJ9R65bLZ3PpJk1W4S1SM2Ccc6-9w) for more details.

Thank you!

**Comment by summerice021** [comment]
> Tilt Brush uses a bloom postprocess pass which is where most of the color comes from. The strokes themselves saturate very quickly to white. See the "Bloom" section of [the documentation](https://docs.google.com/document/d/1YID89te9oDjinCkJ9R65bLZ3PpJk1W4S1SM2Ccc6-9w) for more details.

I see the pdf and there is such word:
"Import the Standard Assets “Effects” package (Assets menu / Import Package / Effects)"

So I download standard asset from [https://assetstore.unity.com/packages/essentials/asset-packs/standard-assets-for-unity-2017-3-32351](url),but I failed to find Bloom script,seems it is not the right asset.

Can you help to find the right asset for me?Thanks a lot!!

**Comment by dubois** [comment]
That was written a long time ago, back in the Unity 5 days. I recommend
using the SE Natural Bloom github package that is linked from the
documentation.
