### ISSUE TITLE
Last Tiltbrush SDK with what version of Unity in 2019

### ISSUE THREAD

**Issue by Scenarman** [googlevr/tilt-brush-toolkit#45]
Hi, there are a lot of Unity version in 2019. With the first 2019.1.0f2 it's OK, I have all my brushes and colors, but with 2019.3.5f1 I lost all of them. What's the last version who work ?
Thank you

**Comment by dubois** [comment]
Hi, Scenarman. The toolkit works on the 2018.4 (LTS, Long Term Support) version of Unity. Once 2019.4 LTS is released, we will be able to look at supporting 2019.

**Comment by Scenarman** [comment]
For me, it' work with 2019.1.0f2. I need that because I use a new tool "Interhaptics" and it doesn't work on 2018.
