### ISSUE TITLE
Can I connect a HTC tracker with Tiltbrush camera ?

### ISSUE THREAD

**Issue by Scenarman** [googlevr/tilt-brush-toolkit#46]
I want connect and synchronize HTC tracker and Tiltbrush camera (spectator camera). Is it possible with Python script or other solution ? I tried in mixed Reality with LIV (on Steam), but it doesn't work...
Thank you

**Comment by dubois** [comment]
This repo and its issue tracker is for the Tilt Brush Toolkit, not for Tilt Brush.

That said, Tilt Brush does not support LIV. It does support SteamVR mixed reality through "externalcamera.cfg", but I am not familiar with how that works.

**Comment by n1ckfg** [comment]
Yup, you just need to configure SteamVR for the tracker:
https://github.com/n1ckfg/ViveTrackerExample

**Comment by Scenarman** [comment]
Yes Paul, I know, but I wonder if it doesn't existe a solution with the toolkit for my question :) 
n1ckfg, I hope it's a new soluce because I had configure my treacker on Steam but it's not enough, it doesn't work with Tiltbrush ;)

**Comment by n1ckfg** [comment]
It's not new, been around since 2016 at least--afaik you have to have three controllers connected for the MR mode to activate. Haven't done it in a while so not sure what combinations of wands vs. trackers and wireless vs. wired connections will work

**Comment by Scenarman** [comment]
Steam recognize all controllers+trackers, the camera problem it's with Tiltbrush and Liv :)

**Comment by dubois** [comment]
Hi Scenarman; to be very clear, Tilt Brush does not support LIV.

**Comment by Scenarman** [comment]
On the LIV discord, everyone tells me the opposite. But I'm willing to believe you, because it's not working for me. 
But this is very bad news for me... Mixcast's not working either, I guess?

A little question, Paul Dubois it's french ? (like me ??:);)
