### ISSUE TITLE
Create PyPi package for the Python code

### ISSUE THREAD

**Issue by Sitin** [googlevr/tilt-brush-toolkit#6]
I suggest to move `bin` and `tests` under `Python` directory and create `setup.py` to turn the Python part of the toolkit to a PyPi package.

Even if we don't want to publish the package right now it would be useful to install it locally.

Here is the [draft commit](https://github.com/Sitin/tilt-brush-toolkit/commit/5a0ec37653a2bdab29efb19792fa4120c23b55ad).

**Comment by dubois** [comment]
We have no plans to upload the package to PyPI, so I'm going to close this.

Adding a setup.py so end-users can more conveniently get the code into their sys.path seems reasonable, so I'm going to leave the pull request open until someone can evaluate it.
